apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  namespace: tsg
  name: HMH-org-location
  description: A collection of all HMH organizations groups
spec:
  type: file
  targets:
    - ./hmh/org.yaml