apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: assignments
  namespace: tsg  
  # This is an extra long description with Markdown
  description: |
    [The HMH Ed platform login](https://www.hmhco.com/ui/login/) is an example of login Interface to get access to learning.
    - Country(drop down list)
    - Organization(drop down list)
    - username
    - password
  links:
    - url: https://scm.eng.hmhco.com/Ed-Learning
      title: Ed-Learning
      icon: github
  annotations:
    datadoghq.com/dashboard-url: datadoghq.com,datadoghq.com/dashboard2
    datadoghq.com/graph-token: someToken      
spec:
  type: web
  lifecycle: production
  owner: tsg-eng4-ed-svc
  system: ed-assignments
  providesApis:
    - ids-grid-api