apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: classcraft-session-data-svc
  namespace: tsg
  description: |
    Manage classcraft session data for classrooms
  annotations:
    datadoghq.com/dashboard-url: https://houghton-mifflin-harcourt.datadoghq.com/dashboard/czh-9bh-q3v/classcraft-session-data-svc
    datadoghq.com/graph-token: '{{ DATADOG_TOKEN }}'
    # datadoghq.com/graph-size: 'large'
    pagerduty.com/integration-key: someToken        
    backstage.io/techdocs-ref: 'url:https://scm.eng.hmhco.com/panahio/classcraft-session-data-service/blob/main'
  links:
    - url: https://scm.eng.hmhco.com/panahio/classcraft-session-data-service
      title: session-data-svc
      icon: github
    - url: https://houghton-mifflin-harcourt.datadoghq.com/dashboard/czh-9bh-q3v/classcraft-session-data-svc
      title: datadog
      icon: dashboard      
  tags:
    - postgres
    - graphql
    - Hasura integration        
spec:
  type: service
  lifecycle: active
  owner: tsg-eng2-can-1
  system: classcraft-system
  providesApis: []
  # providesApis: [session-data-graphql]