apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: classcraft-user-data-svc
  namespace: tsg
  # This is an extra long description with Markdown
  description: |
    Manage classcraft user data for classrooms
  links:
    - url: https://scm.eng.hmhco.com/Ed-Learning/classcraft-user-data-service
      title: user-data-svc Repo
      icon: github
    - url: https://houghton-mifflin-harcourt.datadoghq.com/notebook/8162472/userdata-savestudentdatavalues
      title: datadog
      icon: dashboard      
  annotations:
    pagerduty.com/integration-key: someToken
    pagerduty.com/service-id:  someServiceId
    backstage.io/techdocs-ref: 'url:https://scm.eng.hmhco.com/panahio/classcraft-user-data-service'
    datadoghq.com/dashboard-url: https://houghton-mifflin-harcourt.datadoghq.com/notebook/8162472/userdata-savestudentdatavalues
  tags:
    - hasura
    - postgres
    - mutation
    - subscription

spec:
  type: service
  lifecycle: active
  owner: tsg-eng2-can-1
  system: classcraft-system
  providesApis: []
