apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: classcraft-integration-svc
  # This is an extra long description with Markdown
  description: |
    Pub sub service to Nexus message broker and handle Hasura Actions

  links:
    - url: https://scm.eng.hmhco.com/panahio/classcraft-integration-svc
      title: classcraft-integration-svc
      icon: github
  tags:
  - nexusSdk
  - Kafka
  - hasuraActons
  - s3
spec:
  type: service
  lifecycle: experimental
  owner: theme4
  system: classcraft-system
  providesApis:
      - openapi-oas-action
      - nexus-endpoint-api
