apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: classcraft-integration-svc
  namespace: tsg
  description: |
    Integration service for transactions between HCP, Ed, Hasura, Nexus
  links:
    - url: https://scm.eng.hmhco.com/Ed-Learning/classcraft-integration-svc
      title: classcraft-integration-svc
      icon: github
    - url: https://houghton-mifflin-harcourt.datadoghq.com/dashboard/kb7-pbm-s4y/classcraft-integration-svc
      title: datadog
      icon: dashboard       
  annotations:
    datadoghq.com/dashboard-url: https://houghton-mifflin-harcourt.datadoghq.com/dashboard/kb7-pbm-s4y/classcraft-integration-svc
    datadoghq.com/graph-token: '{{ DATADOG_TOKEN }}'
    pagerduty.com/integration-key: someToken
    pagerduty.com/service-id:  someServiceId
    backstage.io/techdocs-ref: 'url:https://scm.eng.hmhco.com/panahio/classcraft-integration-svc/blob/main'
  tags:
    - nexus
    - kafka
    - actions
    - s3
    - hasura
spec:
  type: service
  lifecycle: emerging
  owner: tsg-eng2-cms-8
  system: classcraft-system
  providesApis: []
#    - openapi-kafka-rest
#    - openapi-oas-action
