apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lift
  namespace: ed-ns  
  # This is an extra long description with Markdown
  description: |
    [The HMH Ed platform login](https://www.hmhco.com/ui/login/) is an example of login Interface to get access to learning.
    - Country(drop down list)
    - Organization(drop down list)
    - username
    - password
  links:
    - url: https://scm.eng.hmhco.com/Ed-Learning
      title: Ed-Learning
      icon: github
spec:
  type: service
  lifecycle: production
  owner: theme7
  system: ed-student-assignments
  providesApis:
    - ids-grid-api