apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: tsg-eng2-can-1
  description: classcraft java & script
  namespace: tsg
spec:
  type: team
  profile:
    displayName: java&script
  parent: ed
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Simon.Belanger
  namespace: tsg  
spec:
  profile:
    displayName: Simon Belanger
    email: simon.belanger@hmhco.com
    picture: https://api.dicebear.com/7.x/avataaars/svg?seed=Luna&backgroundColor=transparent
  memberOf: [tsg-eng2-can-1]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Mathieu.Beauregard
  namespace: tsg  
spec:
  profile:
    displayName: Mathieu Beauregard
    email: mathieu.beauregard@hmhco.com
    picture: https://api.dicebear.com/7.x/avataaars/svg?seed=Leo&backgroundColor=transparent
  memberOf: [tsg-eng2-can-1]