apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: tsg-eng2-can-1
  description: classcraft java & script
  namespace: tsg
spec:
  type: team
  profile:
    displayName: java&script
  parent: ed
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: developer1
  namespace: tsg  
spec:
  profile:
    # Intentional no displayName for testing
    email: developer1@hmhco.com
    picture: https://api.dicebear.com/7.x/avataaars/svg?seed=Luna&backgroundColor=transparent
  memberOf: [tsg-eng2-can-1]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: developer2
  namespace: tsg  
spec:
  profile:
    displayName: Developer 2
    email: developer2@hmh.com
    picture: https://api.dicebear.com/7.x/avataaars/svg?seed=Leo&backgroundColor=transparent
  memberOf: [tsg-eng2-can-1]