apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  namespace: tsg
  name: tsg-eng4-ed-svc
  description: Safal-Sampark
spec:
  type: team
  profile:
    displayName: Safal-Sampark
  links:
    - url: https://confluence.hmhco.com/display/TSGQE/Engineering+Team4
      title: confluent   
  parent: ed
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  namespace: tsg
  name: Ashwini.Jadhav
spec:
  profile:
    # Intentional no displayName for testing
    email: Ashwini.Jadhav3@hmhco.com
    picture: https://api.dicebear.com/7.x/avataaars/svg?seed=Luna&backgroundColor=transparent
  memberOf: [tsg-eng4-ed-svc]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  namespace: tsg
  name: Saurabh.Kurdukar
spec:
  profile:
    displayName: Saurabh Kurdukar
    email: saurabh.kurdukar@hmhco.com
    picture: https://api.dicebear.com/7.x/avataaars/svg?seed=Leo&backgroundColor=transparent
  memberOf: [tsg-eng4-ed-svc]