apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: manager
  namespace: tsg
  description: The HMH Technology Solution Group(TSG)
  links:
    - url: https://hmhco.sharepoint.com/sites/HMH-TSG-Hub/SitePages/Home.aspx
      title: sharepoint
spec:
  type: root
  profile:
    displayName: TSG
  children: [eng]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  namespace: tsg
  name: Peter.George
spec:
  profile:
    displayName: Peter George
    email: peter.george@hmhco.com
    picture: https://api.dicebear.com/7.x/avataaars/svg?seed=Luna&backgroundColor=transparent
  memberOf: [manager]