openapi: 3.1.0
info:
  title: Swagger Service 
  version: 1.0.0
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
    version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://petstore3.swagger.io/api/v3
tags:
  - name: action
    description: Access to Hassura actions
    externalDocs:
      description: Find out more about our store
      url: http://swagger.io
    post:
      tags:
        - action
      summary: Action drived from Hassura
      description: action will be executed
      operationId: hasura-action
      requestBody:
        description: Create a new action and publish to nexus
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Action'
          application/xml:
            schema:
              $ref: '#/components/schemas/Action'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Action'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Action'
            application/xml:
              schema:
                $ref: '#/components/schemas/Action'
        '405':
          description: Invalid input
      security:
        - petstore_auth:
            - write:hassuraAction
            - read:hassuraAction      
