apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: nexus-endpoint-api
  description: nexus  API using Nexus SDK and  allows you to subscribe and publish events to Nexus Kafka Broker
  tags:
    - Kafka
    - pubsub
  links:
    - url: https://scm.eng.hmhco.com/panahio/classcraft-integration-svc/tree/main/build/src/main/java/com/hmhco/classcraft/integration/nexus
      title: Source Code
      icon: code
spec:
  type: asyncapi
  lifecycle: production
  owner: theme4
  definition: |
    asyncapi: 3.0.0
    info:
      title: Nexus Kafka API
      version: 1.0.0
      description: " TBD"
      license:
        name: Apache 2.0
        url: 'https://www.apache.org/licenses/LICENSE-2.0'
    defaultContentType: application/json
    servers:
      production:
        host: 'hmh.nexus.co:{port}'
        protocol: mqtt
        description: Test broker
        variables:
          port:
            description: Secure connection (TLS) is available through port 9993.
            default: '9993'
            enum:
              - '9993'
              - '1883'
        security:
          - $ref: '#/components/securitySchemes/apiKey'
          - type: oauth2
            description: Flows to support OAuth 2.0
            flows:
              implicit:
                authorizationUrl: 'https://authserver.example/auth'
                availableScopes:
                  'streetlights:on': Ability to switch lights on
                  'streetlights:off': Ability to switch lights off
                  'streetlights:dim': Ability to dim the lights
              password:
                tokenUrl: 'https://authserver.example/token'
                availableScopes:
                  'streetlights:on': Ability to switch lights on
                  'streetlights:off': Ability to switch lights off
                  'streetlights:dim': Ability to dim the lights
              clientCredentials:
                tokenUrl: 'https://authserver.example/token'
                availableScopes:
                  'streetlights:on': Ability to switch lights on
                  'streetlights:off': Ability to switch lights off
                  'streetlights:dim': Ability to dim the lights
              authorizationCode:
                authorizationUrl: 'https://authserver.example/auth'
                tokenUrl: 'https://authserver.example/token'
                refreshUrl: 'https://authserver.example/refresh'
                availableScopes:
                  'streetlights:on': Ability to switch lights on
                  'streetlights:off': Ability to switch lights off
                  'streetlights:dim': Ability to dim the lights
            scopes:
              - 'streetlights:on'
              - 'streetlights:off'
              - 'streetlights:dim'
          - $ref: '#/components/securitySchemes/openIdConnectWellKnown'
        tags:
          - name: 'env:production'
            description: This environment is meant for production use case
          - name: 'kind:remote'
            description: This server is a remote server. Not exposed by the application
          - name: 'visibility:public'
            description: This resource is public and available to everyone