apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  namespace: tsg
  name: ids-grid-api
  description: Student - Assignments
  tags:
    - rest
    - proto3  
spec:
  type: grpc
  lifecycle: production
  owner: tsg-eng4-ed-svc
  definition: |


    syntax = "proto3";

    option java_multiple_files = true;
    option java_package = "io.grpc.examples.helloworld";
    option java_outer_classname = "HelloWorldProto";
    option objc_class_prefix = "HLW";

    package helloworld;

    // The greeting service definition.
    service Greeter {
      // Sends a greeting
      rpc SayHello (HelloRequest) returns (HelloReply) {}
    }

    // The request message containing the user's name.
    message HelloRequest {
      string name = 1;
    }

    // The response message containing the greetings
    message HelloReply {
      string message = 1;
    }