apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: classcraft-system
  namespace: tsg
  description: Everything related to classcraft services
  links:
    - url: https://confluence.hmhco.com/pages/viewpage.action?pageId=286503500
      title: Session Organizer
      icon: docs
    - url: https://concourse.tsg.hmhco.com/
      title: Concourse CI
      icon: dashboard           
  tags:
    - microservice
    - hasurra
    - nexus
    - springboot
    - graphql
    - rest
    - react
spec:
  owner: eng
  domain: ed-platform